---
title: "Hydrology simulation"
author: "M. Umit Taner"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
#Load package
library(sacsmaR)
library(dplyr)
```


```{r}

# Load data-files for st-croix system
data(stcroix)

# Date-time preferences
str_date <- as.Date("1970/01/1")
end_date <- as.Date("1980/12/31")
seq_date <- seq.Date(str_date, end_date, by = "day") 
sim_date <- seq.Date(str_date, end_date, by = "day") 
sim_per  <- length(sim_date) 

# HRU info file (lat, lon, area, elev, flowlength, id)
grid_info <- stcroix$hru.info
hru_par   <- stcroix$hru.par
hru_prcp  <- stcroix$prcp.grid
hru_tavg  <- stcroix$tavg.grid

#Parameters
hru_lat     <- unlist(grid_info[,1], use.names = FALSE)
hru_lon     <- unlist(grid_info[,2], use.names = FALSE)
hru_area    <- unlist(grid_info[,3], use.names = FALSE)
hru_elev    <- unlist(grid_info[,4], use.names = FALSE)
hru_flowlen <- unlist(grid_info[,5], use.names = FALSE)

# Set parameters
par_sacsma   <- hru_par[,1:16]
par_petHamon <- hru_par[,17]
par_snow17   <- hru_par[,18:27]
par_routLah  <- hru_par[,28:31]

jday <- lubridate::yday(sim_date)

# #### TEST 1) Check each function individually
pet <- hamon(par = par_petHamon[1], tavg = hru_tavg[[1]],
                lat = hru_lat[[1]], jday = jday)

snowMelt <- snow17(par = par_snow17[1,],
                   prcp = hru_prcp[[1]],
                   tavg = hru_tavg[[1]],
                   elev = hru_elev[[1]],
                   jday = jday)

### SAC MODULE
simflow <- sacsma(par = par_sacsma[1,],
                  prcp = hru_prcp[[1]],
                  pet = pet, lat = hru_lat[1], elev = hru_elev[1])

### ROUTING MODULE
flow <- lohmann(par = par_routLah[1,], flength = hru_flowlen[1])


################# BASIN-WIDE SIMULATION

hru_par <- hru_par %>% as.matrix()

par_sacsma   = hru_par[,1:16] 
par_petHamon = hru_par[,17]  
par_snow17   = hru_par[,18:27] 
par_routLah  = hru_par[,28:31] 


flowR <- hydroSim(
  par.hamon    = hru_par[,17],
  par.snow17   = hru_par[,18:27],
  par.sacsma   = hru_par[,1:16],
  par.lohmann  = hru_par[,28:31],
  tavg.grid    = hru_tavg,
  prcp.grid    = hru_prcp,
  lat.grid     = hru_lat,
  elev.grid    = hru_elev,
  area.grid    = hru_area, 
  flength.grid = hru_flowlen,
  jday = jday)


```


